version: "3.9"
services:
  db:
    ports:
      - "5432:5432"
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: xendit_webhook
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - "0.0.0.0:5672:5672"
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
networks:
  rabbitmq_go_net:
    driver: bridge
